apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-conf
spec:
  replicas: 1
  selector:
    matchLabels:
       app: app-conf
  template:
    metadata:
      labels:
        app: app-conf
    spec:
      containers:
        - name: app-conf
          image: kubedevio/app-variaveis-ambiente:v1
          ports:
            - containerPort: 30000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME_CONFIG
          # envFrom:
          #   - configMapRef:
          #       name: app-config
          # env:
          #   - name: APP_NAME
          #     value: "Minha Aplicação rodando no K3d"
          #   - name: APP_VERSION
          #     value: "2.55"
          #   - name: APP_AUTHOR
          #     value: "Lucas Ferto"
---
apiVersion: v1
kind: Service
metadata:
  name: app-conf
spec:
  selector:
    app: app-conf
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
